name: discover
description: Discover your real coverage with Flutter including not tested Dart files.
version: 0.3.0
repository: https://github.com/PiotrFLEURY/discover

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  file: ^7.0.1
  glob: ^2.1.3
  mason_logger: ^0.3.0
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0

executables:
  discover:
